# Generated by Django 5.2.3 on 2025-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10)),
                ('iata', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('flight_price', models.FloatField(blank=True, null=True)),
                ('hotel_price', models.FloatField(blank=True, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('scraped_at', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
